# frozen_string_literal: true

require "json"
require "fileutils"
require "tmpdir"

require_relative "gallery/helpers"
require_relative "gallery/views/status_text"

require_relative "gallery/sections/controls/calculator"
require_relative "gallery/sections/controls/code_editor"
require_relative "gallery/sections/controls/components"
require_relative "gallery/sections/controls/counter"
require_relative "gallery/sections/controls/cupertino_controls"
require_relative "gallery/sections/controls/material_controls"
require_relative "gallery/sections/controls/responsive_row"
require_relative "gallery/sections/controls/todo"

require_relative "gallery/sections/media/accelerometer"
require_relative "gallery/sections/media/animation"
require_relative "gallery/sections/media/audio"
require_relative "gallery/sections/media/audio_recorder"
require_relative "gallery/sections/media/barometer"
require_relative "gallery/sections/media/battery"
require_relative "gallery/sections/media/browser_context_menu"
require_relative "gallery/sections/media/camera"
require_relative "gallery/sections/media/clipboard"
require_relative "gallery/sections/media/connectivity"
require_relative "gallery/sections/media/file_picker"
require_relative "gallery/sections/media/flashlight"
require_relative "gallery/sections/media/geolocator"
require_relative "gallery/sections/media/gyroscope"
require_relative "gallery/sections/media/magnetometer"
require_relative "gallery/sections/media/map"
require_relative "gallery/sections/media/permission_handler"
require_relative "gallery/sections/media/rive"
require_relative "gallery/sections/media/screen_brightness"
require_relative "gallery/sections/media/screenshot"
require_relative "gallery/sections/media/secure_storage"
require_relative "gallery/sections/media/semantics_service"
require_relative "gallery/sections/media/shake_detector"
require_relative "gallery/sections/media/share"
require_relative "gallery/sections/media/storage_paths"
require_relative "gallery/sections/media/user_accelerometer"
require_relative "gallery/sections/media/video"
require_relative "gallery/sections/media/webview"
require_relative "gallery/sections/media/window"

require_relative "gallery/sections/tools/icon_search"
require_relative "gallery/sections/charts"
require_relative "gallery/sections/drawing"
require_relative "gallery/sections/controls/spinkit"
